CREATE TABLE IF NOT EXISTS artist (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre (
	id SERIAL PRIMARY KEY,
	name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS genre_artist (
	id SERIAL PRIMARY KEY,
	genre_id INTEGER NOT NULL REFERENCES genre(id),
	artist_id INTEGER NOT NULL REFERENCES artist(id),
);

CREATE TABLE IF NOT EXISTS album (
	id SERIAL PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	releaseyear INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS album_artist (
	id SERIAL PRIMARY KEY,
	album_id INTEGER NOT NULL REFERENCES album(id),
	artist_id INTEGER NOT NULL REFERENCES artist(id),
);

CREATE TABLE IF NOT EXISTS track (
	id SERIAL PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	album_id INTEGER NOT NULL REFERENCES album(id),
	duration NUMERIC(4,2) NOT NULL
);


CREATE TABLE IF NOT EXISTS compilation (
	id SERIAL PRIMARY KEY,
	name VARCHAR(120) NOT NULL,
	releaseyear INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS compilation_track (
	id SERIAL PRIMARY KEY,
	track_id INTEGER NOT NULL REFERENCES track(id),
	compilation_id INTEGER NOT NULL REFERENCES compilation(id)
);
